import { ROLES } from "./roles";

export const PERMISSIONS = {
  MANAGE_USERS: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  MANAGE_CONTENT: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
  MANAGE_SETTINGS: [ROLES.SUPER_ADMIN],
  VIEW_DASHBOARD: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
} as const;
