import mongoose from "mongoose";
export declare const JobModel: mongoose.Model<{
    title: string;
    type: string;
    company: string;
    source: string;
    sourceUrl: string;
    location: string;
    salaryMin: number;
    salaryMax: number;
    expMin: number;
    expMax: number;
    skills: string;
    description: string;
    requirements: string;
    benefits: string;
    companyEmail: string;
    status: "active" | "inactive" | "expired" | "draft";
    applications: number;
    remote: boolean;
    hybrid: boolean;
    isPremium: boolean;
    premium: boolean;
    isFeatured: boolean;
    featured: boolean;
    isUrgent: boolean;
    isSponsored: boolean;
    postPhoto: string;
    isDeleted: boolean;
    expiryDate?: NativeDate | null;
    deletedAt?: NativeDate | null;
} & mongoose.DefaultTimestampProps, {}, {}, {
    id: string;
}, mongoose.Document<unknown, {}, {
    title: string;
    type: string;
    company: string;
    source: string;
    sourceUrl: string;
    location: string;
    salaryMin: number;
    salaryMax: number;
    expMin: number;
    expMax: number;
    skills: string;
    description: string;
    requirements: string;
    benefits: string;
    companyEmail: string;
    status: "active" | "inactive" | "expired" | "draft";
    applications: number;
    remote: boolean;
    hybrid: boolean;
    isPremium: boolean;
    premium: boolean;
    isFeatured: boolean;
    featured: boolean;
    isUrgent: boolean;
    isSponsored: boolean;
    postPhoto: string;
    isDeleted: boolean;
    expiryDate?: NativeDate | null;
    deletedAt?: NativeDate | null;
} & mongoose.DefaultTimestampProps, {
    id: string;
}, {
    timestamps: true;
}> & Omit<{
    title: string;
    type: string;
    company: string;
    source: string;
    sourceUrl: string;
    location: string;
    salaryMin: number;
    salaryMax: number;
    expMin: number;
    expMax: number;
    skills: string;
    description: string;
    requirements: string;
    benefits: string;
    companyEmail: string;
    status: "active" | "inactive" | "expired" | "draft";
    applications: number;
    remote: boolean;
    hybrid: boolean;
    isPremium: boolean;
    premium: boolean;
    isFeatured: boolean;
    featured: boolean;
    isUrgent: boolean;
    isSponsored: boolean;
    postPhoto: string;
    isDeleted: boolean;
    expiryDate?: NativeDate | null;
    deletedAt?: NativeDate | null;
} & mongoose.DefaultTimestampProps & {
    _id: mongoose.Types.ObjectId;
} & {
    __v: number;
}, "id"> & {
    id: string;
}, mongoose.Schema<any, mongoose.Model<any, any, any, any, any, any, any>, {}, {}, {}, {}, {
    timestamps: true;
}, {
    title: string;
    type: string;
    company: string;
    source: string;
    sourceUrl: string;
    location: string;
    salaryMin: number;
    salaryMax: number;
    expMin: number;
    expMax: number;
    skills: string;
    description: string;
    requirements: string;
    benefits: string;
    companyEmail: string;
    status: "active" | "inactive" | "expired" | "draft";
    applications: number;
    remote: boolean;
    hybrid: boolean;
    isPremium: boolean;
    premium: boolean;
    isFeatured: boolean;
    featured: boolean;
    isUrgent: boolean;
    isSponsored: boolean;
    postPhoto: string;
    isDeleted: boolean;
    expiryDate?: NativeDate | null;
    deletedAt?: NativeDate | null;
} & mongoose.DefaultTimestampProps, mongoose.Document<unknown, {}, {
    title: string;
    type: string;
    company: string;
    source: string;
    sourceUrl: string;
    location: string;
    salaryMin: number;
    salaryMax: number;
    expMin: number;
    expMax: number;
    skills: string;
    description: string;
    requirements: string;
    benefits: string;
    companyEmail: string;
    status: "active" | "inactive" | "expired" | "draft";
    applications: number;
    remote: boolean;
    hybrid: boolean;
    isPremium: boolean;
    premium: boolean;
    isFeatured: boolean;
    featured: boolean;
    isUrgent: boolean;
    isSponsored: boolean;
    postPhoto: string;
    isDeleted: boolean;
    expiryDate?: NativeDate | null;
    deletedAt?: NativeDate | null;
} & mongoose.DefaultTimestampProps, {
    id: string;
}, Omit<mongoose.DefaultSchemaOptions, "timestamps"> & {
    timestamps: true;
}> & Omit<{
    title: string;
    type: string;
    company: string;
    source: string;
    sourceUrl: string;
    location: string;
    salaryMin: number;
    salaryMax: number;
    expMin: number;
    expMax: number;
    skills: string;
    description: string;
    requirements: string;
    benefits: string;
    companyEmail: string;
    status: "active" | "inactive" | "expired" | "draft";
    applications: number;
    remote: boolean;
    hybrid: boolean;
    isPremium: boolean;
    premium: boolean;
    isFeatured: boolean;
    featured: boolean;
    isUrgent: boolean;
    isSponsored: boolean;
    postPhoto: string;
    isDeleted: boolean;
    expiryDate?: NativeDate | null;
    deletedAt?: NativeDate | null;
} & mongoose.DefaultTimestampProps & {
    _id: mongoose.Types.ObjectId;
} & {
    __v: number;
}, "id"> & {
    id: string;
}, unknown, {
    title: string;
    type: string;
    company: string;
    source: string;
    sourceUrl: string;
    location: string;
    salaryMin: number;
    salaryMax: number;
    expMin: number;
    expMax: number;
    skills: string;
    description: string;
    requirements: string;
    benefits: string;
    companyEmail: string;
    status: "active" | "inactive" | "expired" | "draft";
    applications: number;
    remote: boolean;
    hybrid: boolean;
    isPremium: boolean;
    premium: boolean;
    isFeatured: boolean;
    featured: boolean;
    isUrgent: boolean;
    isSponsored: boolean;
    postPhoto: string;
    isDeleted: boolean;
    expiryDate?: NativeDate | null;
    deletedAt?: NativeDate | null;
    createdAt: NativeDate;
    updatedAt: NativeDate;
} & {
    _id: mongoose.Types.ObjectId;
} & {
    __v: number;
}>, {
    title: string;
    type: string;
    company: string;
    source: string;
    sourceUrl: string;
    location: string;
    salaryMin: number;
    salaryMax: number;
    expMin: number;
    expMax: number;
    skills: string;
    description: string;
    requirements: string;
    benefits: string;
    companyEmail: string;
    status: "active" | "inactive" | "expired" | "draft";
    applications: number;
    remote: boolean;
    hybrid: boolean;
    isPremium: boolean;
    premium: boolean;
    isFeatured: boolean;
    featured: boolean;
    isUrgent: boolean;
    isSponsored: boolean;
    postPhoto: string;
    isDeleted: boolean;
    expiryDate?: NativeDate | null;
    deletedAt?: NativeDate | null;
    createdAt: NativeDate;
    updatedAt: NativeDate;
} & {
    _id: mongoose.Types.ObjectId;
} & {
    __v: number;
}>;
//# sourceMappingURL=model.d.ts.map